version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: org.eclipse.jetty:jetty-maven-plugin
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: com.eduworks:org.credentialengine
    versions:
    - 3.1.2
    - 3.1.3
    - 3.1.7
  - dependency-name: com.eduworks:cass.adapter
    versions:
    - 3.1.2
    - 3.1.3
    - 3.1.7
  - dependency-name: com.eduworks:cass.import
    versions:
    - 3.1.2
    - 3.1.3
    - 3.1.7
  - dependency-name: com.eduworks:cass.rollup
    versions:
    - 3.1.2
    - 3.1.3
    - 3.1.7
  - dependency-name: com.eduworks:ebac.identity
    versions:
    - 3.1.2
    - 3.1.3
    - 3.1.7
  - dependency-name: com.eduworks:cass.competency
    versions:
    - 3.1.2
    - 3.1.3
    - 3.1.7
  - dependency-name: com.eduworks:forge
    versions:
    - 3.1.2
    - 3.1.3
    - 3.1.7
  - dependency-name: com.eduworks:kbac.skyrepo
    versions:
    - 3.1.2
    - 3.1.3
    - 3.1.7
  - dependency-name: com.eduworks:ew.db.mapdb
    versions:
    - 5.16.4
  - dependency-name: com.eduworks:ew.levr.rdf
    versions:
    - 5.16.4
  - dependency-name: com.eduworks:ew.levr.net
    versions:
    - 5.16.4
  - dependency-name: com.eduworks:ew.levr.db.mapdb
    versions:
    - 5.16.4
  - dependency-name: com.eduworks:ew.levr.security
    versions:
    - 5.16.4
  - dependency-name: com.eduworks:ew.levr.base
    versions:
    - 5.16.4
