language: node_js
node_js:
  - 16
before_install:
  - curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -;
  - sudo apt-get install -y nodejs
  - sudo npm install -g pm2
script: "npm run test:deps && npm run test:sudostart && sleep 8 && npm run mocha"
sudo: required
notifications:
  slack:
    secure: pfMwKt+N+noLG7FRoELQ0+69CVROA4J7mq73e3IrUq6m9ASR6AUk10WZfzWjXGAIA+h/+mjLDPOD8cUcjaawfuDHG0BiDBD+rZWBU1a3XeEtgyXAMp3JZNt9xj3FylsvYxGGcyHiUOee7JKYS5hq58CCH+iYeyK0d2Ne5UberSzLHzV4JS0UJeqFYY7E9fDgZ4yCkMPxSqMMPS4XbLGjyEyVcVpzQFVgR77uArCLrZqHygz6WGuTBIfml9YWIx4pBa1ipAEkOlzqcI35F/nQIKqO5yOjLt6fHM65bKg30AT59YEsSDKy1JYY55n0yvawVrLKNrWck9RAOGXwJzBjiWv2AvXbUVgXVIDL6HEZoVBSu2I19M6jVsq72sQJhB2otQwPiDQhQwZvIgNghf7xyhu45p/hX/p9sH6UguHNUDRWxxpak9pIg/dbuTTomEpgWNDC+HgbLOc8JUQYQRF2FbXr9Mhu1Pg/NOlUZ6sWGNEgJyEzOWwkR8U8EOv059WxgdGBi05a49491255IYaRwwS+6twZkelDxlPLB0ucp1XQ3jshu/HzBQ/ZfjJe/U4gHG/Gt3W1zLrfDrjQ1UH9hiXvEXHBKr7/PjXNAOwA+AG4kbBJ50hUcXqCPx3ZbCsrgS5y2Po8CNDwa5hu6+U6kE3OzvB02LuXYq0D1O7lmO4=
after_failure: "sudo pm2 logs --nostream --lines 1000"
deploy:
  provider: releases
  api_key:
    secure: y0AeI/3KGRm/h1WSAFji1mzABE9qBiZYmX0jat2URQvPZNgz6QSA0KDe6ZO2OGLy3VO1fCgAi7Aw23SWHonE0FCUBxxzZW/+Gtj19IEsIHC2W19N22lBV0c44TPlKe+LoUOH6RhUPYYO7hCvo2+IE4CtylBYnVvVP+SOJIbRpdc7Ky+SjHdxbbK6XUEo8rfvDsZl/UQZiKTf+Ydezs6yktGFT3PRsPUU7YXqBm0OC/2G6LeADC70YByuXmlADWcDsiyaE44DN+1EbkAWRkXQ508ckvM8jyKQ5AeC1jcGdpbwXT3jYp2hTFYThtHuGaidU9tKlP+7UhuUm+iYPQXSIKdVe0yQjZkrWHzXfWFfQ2SkZiqTwLSsbejzB03ozPBtq/Fg7BA+epTXGgN6iKjjC/i5Rv2/9RbtxGqGmlEuxENPYw8KT2yt5AwgOoHbhDiXMcMDXrRY1STboskBY95tKYY3GXBDpWNITtxYl9qzWsfrxbDFu0KjEeZWmQhFC2LFRMzAKVH+rER8sWIyqvregvis75nw6u6izyLDaKcvp7hdbyykxCWnqge9zGw91J3wHEdM49wMUr6f/kTQRGzDv/79afNN97ZqCriqBo0HJg9eIwqyz3kYv7aKlkudjkjKqd0WbVFy7+caJRYKcPzG7O4pJGhEtIUCXcPtKV2iZgI=
  on:
    repo: cassproject/CASS
    tags: true
