version: '3'
services:
  apache2:
    image: httpd:2.4
    container_name: apache2
    volumes:
      - ./docker-configure.apache2.config:/usr/local/apache2/conf/httpd.conf
    ports:
      - 80:80
    restart: always
    depends_on:
      - cass
      - keycloak
    networks:
      - esnet
  cass:
    build:
      context: .
      dockerfile: docker/distributed/tomcat-alpine/Dockerfile
    container_name: cass
    environment:
      - CASS_LOOPBACK=http://172.17.0.1/api/
      - ELASTICSEARCH_ENDPOINT=http://elasticsearch:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - etc:/usr/local/tomcat/etc/
    networks:
      - esnet
    depends_on:
      - elasticsearch
      - elasticsearch2
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.12
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.12
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
  mysql-keycloak:
    image: mysql:5.7
    container_name: mysql-keycloak
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    networks:
      - esnet
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql-keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: cass
      KEYCLOAK_PASSWORD: cass
      KEYCLOAK_HOSTNAME: 172.17.0.1
      KEYCLOAK_HTTP_PORT: 80
    depends_on:
      - mysql-keycloak
    networks:
      - esnet
volumes:
  etc:
    driver: local
  esdata1:
    driver: local
  esdata2:
    driver: local
  mysql_data:
    driver: local

networks:
  esnet: