version: '2'
services:
  cass:
    build:
      context: .
      dockerfile: docker/distributed/tomcat-alpine/Dockerfile
    container_name: cass
    environment:
      - CASS_LOOPBACK=http://192.168.8.162:8080/api/
      - ELASTICSEARCH_ENDPOINT=http://elasticsearch:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - etc:/usr/local/tomcat/etc/
    ports:
      - 8080:8080
    networks:
      - esnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.12
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.12
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet

volumes:
  etc:
    driver: local
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet: