version: '3'
services:
  cass:
    build:
      context: .
    container_name: cass
    networks:
      - esnet
    ports:
      - 80:80
    environment:
      - CASS_LOOPBACK=http://cass/api/
      - ELASTICSEARCH_ENDPOINT=http://elasticsearch:9200
      - PORT=80
      # - CASS_OIDC_ENABLED=true # turns on open id login
      # - CASS_OIDC_ISSUER_BASE_URL=http://keycloak:8080/auth/realms/master/ # point at your keycloak realm
      # - CASS_OIDC_CLIENT_ID=cass # name of your keycloak client
      # - CASS_OIDC_SECRET=M2nn59wDxkwUZ9SVEVAJADYnUeKP78vU # secret from your keycloak client
      # - CASS_OIDC_BASE_URL=http://localhost/ # where to redirect after login
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - etc:/app/etc
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elasticsearch
    networks:
      - esnet
    environment:
      - cluster.name=docker-cluster
      - node.name=node-1
      - cluster.max_shards_per_node=3000
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms6g -Xmx6g"
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  # UNCOMMENT FOR KEYCLOAK IF USING OIDC
  # mysql-keycloak:
  #   image: mysql:5.7
  #   container_name: mysql-keycloak
  #   networks:
  #     - esnet
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: keycloak
  #     MYSQL_USER: keycloak
  #     MYSQL_PASSWORD: password
  # keycloak:
  #   image: jboss/keycloak
  #   container_name: keycloak
  #   networks:
  #     - esnet
  #   ports:
  #     - 8080:8080
  #   environment:
  #     DB_VENDOR: MYSQL
  #     DB_ADDR: mysql-keycloak
  #     DB_DATABASE: keycloak
  #     DB_USER: keycloak
  #     DB_PASSWORD: password
  #     KEYCLOAK_USER: cass
  #     KEYCLOAK_PASSWORD: cass
  #     KEYCLOAK_HOSTNAME: host.docker.internal
  #     KEYCLOAK_HTTP_PORT: 8080
  #   depends_on:
  #     - mysql-keycloak
volumes:
  etc:
    driver: local
  esdata1:
    driver: local
  esdata2:
    driver: local
  mysql_data:
    driver: local
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  psql_data:
    driver: local

networks:
  esnet: