version: '3'
services:
  apache2:
    build:
      context: .
      dockerfile: docker/dev/apache2/Dockerfile
    container_name: apache2
    ports:
      - 80:80
    restart: always
    depends_on:
      - cass
    networks:
      - esnet
  cass:
    build:
      context: .
    container_name: cass
    environment:
      - CASS_LOOPBACK=http://localhost/api/
      - ELASTICSEARCH_ENDPOINT=http://elasticsearch:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
#      - ./docker/distributed/tomcat-alpine/server.xml:/usr/local/tomcat/conf/server.xml
      - etc:/app/etc
    networks:
      - esnet
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - node.name=node-1
      - cluster.max_shards_per_node=3000
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms6g -Xmx6g"
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - esnet
#  elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.12
#     container_name: elasticsearch
#     environment:
#       - cluster.name=docker-cluster
#       - bootstrap.memory_lock=true
#       - cluster.max_shards_per_node=3000
#       - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
#     ports:
#       - 9200:9200
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     volumes:
#       - ./data:/usr/share/elasticsearch/data
#     networks:
#       - esnet
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.12
#    container_name: elasticsearch
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - xpack.security.enabled=false
#      - xpack.monitoring.collection.interval=-1
#      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
#    ports:
#      - 9200:9200
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - ./data:/usr/share/elasticsearch/data
#    networks:
#      - esnet
volumes:
  etc:
    driver: local
  esdata1:
    driver: local
  esdata2:
    driver: local
  mysql_data:
    driver: local
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  psql_data:
    driver: local

networks:
  esnet: